name: paylink_payment
description: A Flutter Package designed to simplify the integration of Paylink's payment gateway into Flutter applications. It provides a streamlined way to handle payments within your Flutter app.
version: 1.0.1
homepage: https://paylink.sa
repository: https://github.com/sultan-algarbi-paylink/paylink-flutter-package.git
documentation: https://developer.paylink.sa/
topics:
  - payment
  - paylink
  - mada
  - stcpay

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  webview_flutter: ^4.7.0
  http: ^1.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
