name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Responds to tags like v1.0.0
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.3'  # Specify your Flutter version

      - name: Get dependencies
        run: flutter pub get  # Use flutter pub instead of dart pub